### PR TITLE
use only alias field properties

### LINKED ISSUE #118: AliasFieldPlugin.apply + lodash: resolving the wrong toString
When resolving `"./toString"` from `lodash`, [data2 on AliasFieldPlugin.js](https://github.com/webpack/enhanced-resolve/blob/c0797bbcb5d46a44930887c49dc5378b5527cd7a/lib/AliasFieldPlugin.js#L30) is removing the `./` from `"./toString"` of `lodash`, causing `fieldData` to get the default function `toString()` of every object.

Resulting in:
```shell
       var idxQuery = identifier.indexOf("?");
                                  ^

TypeError: identifier.indexOf is not a function
    at Resolver.parse (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:181:28)
    at Resolver.<anonymous> (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/ParsePlugin.js:17:25)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/tapable/lib/Tapable.js:256:13)
    at runNormal (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:130:20)
    at Resolver.doResolve (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:116:3)
    at Resolver.<anonymous> (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:12)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/tapable/lib/Tapable.js:256:13)
    at runNormal (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:130:20)
    at Resolver.doResolve (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:116:3)
    at Resolver.<anonymous> (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/AliasFieldPlugin.js:49:12)
```

Something I couldn't find is: Who is calling the `AliasFieldPlugin`?

A simple and easy fix was to do something like this:
```javascript
if (typeof data === 'function') {
    return callback();
}
```

**OBS:** I'm also using [Haul](https://github.com/callstack/haul), which uses an older version of `webpack`, but still the latest version of `enhanced-resolve`

| Using        | Version           |
| ------------- |-------------|
| npm     | 5.4.2 |
| webpack      | 2.7.0      | 
| enhanced-resolve | 3.4.1   |
| lodash      | 4.17.4      | 
| haul   | 1.0.0-beta.5   |

### PR DESCRIPTION
**Pull request by vankop**
prevent checking object prototype properties

fixes #118

### CODE REVIEW

File: lib/AliasFieldPlugin.js [hunk 1]
```diff
@@ -49,9 +49,17 @@ module.exports = class AliasFieldPlugin {
...
-				const data = typeof data1 !== "undefined" ? data1 : data2;
+				const data = Object.prototype.hasOwnProperty.call(
+					fieldData,
+					innerRequest
+				)
+					? fieldData[innerRequest]
+					: Object.prototype.hasOwnProperty.call(
+							fieldData,
+							innerRequest.replace(/^\.\//, "")
+					  )
```
Comment (sokra) [inline lib/AliasFieldPlugin.js:60]:
```suggestion
					: innerRequest.startsWith("./") && Object.prototype.hasOwnProperty.call(
							fieldData,
							innerRequest.slice(2)
					  )
```

**Comment by vankop** [comment]
it exports/imports field we using enumerable keys only, so it should be safe

**Review by sokra — CHANGES_REQUESTED** [review]
