### PR TITLE
RFC: perform resolution without logging and re-run with logging when failing.

### LINKED ISSUE #88: RFC Performance Improvement Opportunity
**TLDR:** Removing `createInnerCallback` sees a 2x performance boost.

I've been doing a lot of profiling of our webpack builds to see if there are any savings to be had. While doing this I noticed that there is a ton of garbage collection happening, and through that I found my way to this repository.

It seems that `createInnerCallback` creates many large arrays (full of strings) that go unused unless you're passing the `--verbose` flag, and your build has errors.  There may be other use cases, but that's all I've been able to find.

How can we limit the impact here?  I'd love to remove this log entirely as I don't see the value of it as an end user of webpack (webpack 3? 🤞 ), especially since disabling nets a huge performance win.  If that's not possible can we expose an option to disable?

## Charts!

 - It's a little bit difficult to highlight, but notice in this call stack that after each `loggingCallbackWrapper` there is a garbage collection event.

image

 - Here the calls to `createInnerCallback` have been removed (no more garbage collection).

image

Bottom up profile of our build before any changes:
image

After removing all the `createInnerCallback` calls:
image

Removing `createInnerCallback` calls + running with `--max-semi-space-size=1000`:
image

### PR DESCRIPTION
**Pull request by mikesherov**
Fixes #88 

ping @TheLarkInn @sokra would love some input cc @gdborton

### CODE REVIEW

File: lib/Resolver.js [hunk 1]
```diff
@@ -78,6 +78,19 @@ Resolver.prototype.resolve = function resolve(context, path, request, callback)
 	}, null));
 };
 
+Resolver.prototype.doResolveWithErrorLogging = function doResolveWithErrorLogging(type, request, message, callback, options) {
+	var optionsWithoutLog = {
+		stack: options.stack,
+		missing: options.missing
+	};
+
+	this.doResolve(type, request, message, createInnerCallback((err, result) => {
```
Comment (gdborton) [inline lib/Resolver.js]: Do we need this outer `createInnerCallback` call? I know it isn't doing much, but this code path is hit a lot.

**Comment by gdborton** [comment]
Seems legit to me. Thanks for picking this up!

File: lib/Resolver.js (hunk 1 above)
Comment (mikesherov) [inline lib/Resolver.js]: My main concern was compatibility, it still needs to compare options.stack with callback.stack:

```
if(!log) {
		if(options.stack !== callback.stack) {
			var callbackWrapper = function callbackWrapper() {
				return callback.apply(this, arguments);
			};
			callbackWrapper.stack = options.stack;
			callbackWrapper.missing = options.missing;
			return callbackWrapper;
		}
		return callback;
	}
```

Comment (mikesherov) [inline lib/Resolver.js]: basically, it returns the old function after 2 conditionals if everything is OK, so it's extremely low overhead. Avoiding the GC is the huge win you discovered. I think we can afford the 2 correctness checks for now, and if it still remains a perf issue, address in a follow up... thoughts?

Comment (gdborton) [inline lib/Resolver.js]: That makes sense.

This is probably a micro optimization that likely has little to no impact, but I was just thinking that we wouldn't need the `callbackWrapper.stack` and `callbackWrapper.missing` with this code path anyway, since we recall `this.doResolve` w/ `createInnerCallback` on the error case.

Comment (mikesherov) [inline lib/Resolver.js]: Tests fail without it that it fails to throw errors with correct messages otherwise. I was on the same train of thought as you!

File: lib/Resolver.js [hunk 2]
```diff
@@ -71,11 +71,24 @@ Resolver.prototype.resolve = function resolve(context, path, request, callback)
...
 		missing: missing,
 		stack: callback.stack
-	}, null));
+	});
+};
+
+Resolver.prototype.doResolveWithErrorLogging = function doResolveWithErrorLogging(type, request, message, callback, options) {
+	var optionsWithoutLog = {
+		stack: options.stack,
+		missing: options.missing
```
Comment (sokra) [inline lib/Resolver.js]: I case of an error, `stack` and `missing` are written twice.

File: lib/Resolver.js [hunk 3]
```diff
@@ -71,11 +71,24 @@ Resolver.prototype.resolve = function resolve(context, path, request, callback)
...
-	return this.doResolve("resolve", obj, message, createInnerCallback(onResolved, {
+	return this.doResolveWithErrorLogging("resolve", obj, message, onResolved, {
 		log: writeLog,
 		missing: missing,
 		stack: callback.stack
-	}, null));
+	});
+};
+
+Resolver.prototype.doResolveWithErrorLogging = function doResolveWithErrorLogging(type, request, message, callback, options) {
```
Comment (sokra) [inline lib/Resolver.js]: I guess further optimization can be done if this is inlined into `resolve`. i. e. `missing` is only needed for the error run if `callback.missing` is unset.

**Comment by sokra** [comment]
There are no tests for the log result yet. It's would be great to add some.

File: lib/AliasFieldPlugin.js [hunk 4]
```diff
@@ -41,11 +40,11 @@ AliasFieldPlugin.prototype.apply = function(resolver) {
 			path: request.descriptionFileRoot,
 			request: data
 		});
-		resolver.doResolve(target, obj, "aliased from description file " + request.descriptionFilePath + " with mapping '" + innerRequest + "' to '" + data + "'", createInnerCallback(function(err, result) {
+		resolver.doResolveWithErrorLogging(target, obj, "aliased from description file " + request.descriptionFilePath + " with mapping '" + innerRequest + "' to '" + data + "'", function(err, result) {
```
Comment (mikesherov) [inline lib/AliasFieldPlugin.js]: `doResolve` skips the "run twice", `resolve` doesn't unless I'm misunderstanding?

File: lib/Resolver.js (hunk 2 above)
Comment (mikesherov) [inline lib/Resolver.js]: Does that mean I should run without `missing` and `stack` first? Or just `stack`?

**Comment by mikesherov** [comment]
@sokra I'll definitely add a bunch of tests. Just wanted to ensure I had the approach correct.

File: lib/AliasFieldPlugin.js (hunk 4 above)
Comment (sokra) [inline lib/AliasFieldPlugin.js]: This is the control flow when using `doResolveWithErrorLogging` inside of plugins:

```
resolve -> doResolveWithErrorLogging -> SomePlugin -> doResolveWithErrorLogging -> SomeOtherPlugin -> error
                                                                          v-----------------------------+
                                                                     (with log) -> SomeOtherPlugin -> error
                               v------------------------------------------*-----------------------------+
                          (with log) -> SomePlugin -> doResolveWithErrorLogging -> SomeOtherPlugin -> error
                                                                          v-----------------------------+
                                                                     (with log) -> SomeOtherPlugin -> error
   v---------------------------*------------------------------------------*-----------------------------+
```

This is the control flow when using doResolve:

```
resolve -> doResolveWithErrorLogging -> SomePlugin -> doResolve -> SomeOtherPlugin -> error
                               v--------------------------------------------------------+
                          (with log) -> SomePlugin -> doResolve -> SomeOtherPlugin -> error
   v---------------------------*--------------------------------------------------------+
```

Comment (mikesherov) [inline lib/AliasFieldPlugin.js]: Got it.

Comment (mikesherov) [inline lib/AliasFieldPlugin.js]: So this means I should just get rid of createInnerCallback here.

Comment (mikesherov) [inline lib/AliasFieldPlugin.js]: ?

Comment (sokra) [inline lib/AliasFieldPlugin.js]: No the createInnerCallback is ok. Just leave the calls in the plugins in the original version and it should be fine.

File: lib/createInnerCallback.js [hunk 5]
```diff
@@ -5,7 +5,7 @@
 module.exports = function createInnerCallback(callback, options, message, messageOptional) {
 	var log = options.log;
 	if(!log) {
-		if(options.stack !== callback.stack) {
+		if(options.stack !== callback.stack || options.missing !== callback.missing) {
```
Comment (gdborton) [inline lib/createInnerCallback.js]: Is this an unrelated change?

File: lib/AliasFieldPlugin.js (hunk 4 above)
Comment (gdborton) [inline lib/AliasFieldPlugin.js]: I'm trying to understand what's to be changed here. From the sound of it `.resolve` is the only function directly called via the build, then all the `.doResolve` calls are made from Resolver plugins... is that right?

If so it would seem to me the only thing that this PR needs to change is `.resolve` around line 74 to be something like...
```javascript
return this.doResolve("resolve", obj, message, function(err, result) {
	if (err) {
		return this.doResolve("resolve", obj, message, createInnerCallback(onResolved, {
			log: writeLog,
			missing: missing,
			stack: callback.stack
		}, null));
	}

	return onResolved(err, result);
});
```

File: test/missing.js [hunk 6]
```diff
@@ -45,6 +51,46 @@ describe("missing", function() {
...
+		});
+		it("should report missing files exactly once when trying to resolve " + testCase[1], function(done) {
+			var callback = function(err, filename) {
+				if(err) {
+					var missing = err.missing.sort();
+					var isSame = true;
+					for(var i = 0; i < missing.length - 1; i += 2) {
+						isSame = isSame && (missing[i] === missing[i + 1]);
+					}
+					isSame.should.not.be.true('missing file names should not be repeated');
```
Comment (gdborton) [inline test/missing.js]: Can you change this to use `"`?

**Comment by gdborton** [comment]
@sokra Can you take another look?  This reduces our build times by roughly 30% from `2m47s` to `1m50s`, I added a `console.log` above `theLog.push` line, and it doesn't get called anymore.

@mikesherov Can you add the below to a .eslintrc file in `./test`? That'll allow for the testing globals that codacy is complaining about.

```json
{
  "globals": {
    "it": true,
    "describe": true,
    "beforeEach": true,
    "afterEach": true,
    "context": true,
    "before": true,
    "after": true,
  }
}
```

**Comment by sokra** [comment]
Thanks

**Comment by Mayank1791989** [comment]
@mikesherov @sokra  Thanks for the update. 
Tried new version today reduces my initial build time from ~60sec to ~28sec.
