### PR TITLE
fix #238

### LINKED ISSUE #238: incorrect resolve
Good day!

Is there a possibility that the `resolve.modules` implementation changed in webpack5? I upgraded my project and after a few struggles I found out that I have to change this option to make it work.

Here are a few details to the problem:
This is how the webpack `resolve` object looks in webpack4.
```js
resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
    alias: {
      src: path.resolve('./src'),
    },
    modules: ['src/b',  'src/a', 'src/common', 'node_modules'],
},
```

The file structure of my project:
```
project/
└── src/
     ├── common/
     │   └── config/
     │       └── myObjectFile.js
     ├── a/
     │   ├── config.js
     │   └── config/
     │       └── someOtherFile.js
     └── b/
```
<details>
  <summary>The content of the <code>./src/common/config/myObjectFile.js</code> file:</summary>

```js
export default {
  someProp: {
    //...
  },
  //...
}
```

</details>

<details>
  <summary>The content of the <code>./src/a/config.js</code> file:</summary>

```js
const config = {
  configA: {
    //...
  },
  //...
};

module.exports = config;
```

</details>

In the project I do a import which looks like this: 
```js
import myObject from 'config/myObjectFile';
```
This should and is resolved in webpack4 like this: `./src/common/config/myObjectFile.js`. 
In webpack5 on the other hand I'm getting this: `./src/a/config.js`.

Only after I changed (reversed) the order of the `resolve.modules` array it worked as intended:
```js
resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
    alias: {
      src: path.resolve('./src'),
    },
    modules: ['node_modules', 'src/common', 'src/a', 'src/b'],
},
```

Is this intended behavior? 
Is my "fix" even valid or is the problem something completely different?

Thank you!

_Originally posted by @KingSora in https://github.com/webpack/webpack/issues/9802#issuecomment-677401611_

### PR DESCRIPTION
**Pull request by vankop**
fixes #238

### CODE REVIEW

File: test/alias.js [hunk 1]
```diff
@@ -120,16 +120,6 @@ describe("alias", function() {
 					"    No description file found in / or above",
 					"    resolve as module",
 					"      looking for modules in /",
-					"        single file module",
```
Comment (sokra) [inline test/alias.js:123]: :+1: This looks correct. `/a.js` etc. should not be resolved with this request.

File: test/dependencies.js [hunk 2]
```diff
@@ -47,22 +47,12 @@ describe("dependencies", function() {
...
 				"/package.json",
-				"/a/node_modules/package.json",
-				"/a/b/node_modules/package.json",
 				// missing modules directories
 				"/a/b/c/node_modules",
 				// not found in modules directories
-				"/modules/package.json",
 				// missing single file modules
 				"/modules/module",
-				"/modules/module.json",
```
Comment (sokra) [inline test/dependencies.js:58]: ✅

File: test/dependencies.js [hunk 3]
```diff
@@ -47,22 +47,12 @@ describe("dependencies", function() {
...
-				"/modules/module.js",
 				"/a/b/node_modules/module",
-				"/a/b/node_modules/module.json",
```
Comment (sokra) [inline test/dependencies.js:61]: ✅

File: test/dependencies.js [hunk 4]
```diff
@@ -47,22 +47,12 @@ describe("dependencies", function() {
 				"/a/b/package.json",
 				"/a/package.json",
 				"/package.json",
-				"/a/node_modules/package.json",
```
Comment (sokra) [inline test/dependencies.js:50]: ✅ These package.json origin from trying to resolve as single file module. We don't need them

File: test/dependencies.js [hunk 5]
```diff
@@ -47,22 +47,12 @@ describe("dependencies", function() {
...
-				"/a/b/node_modules/package.json",
 				// missing modules directories
 				"/a/b/c/node_modules",
 				// not found in modules directories
-				"/modules/package.json",
```
Comment (sokra) [inline test/dependencies.js:55]: ✅ These package.json origin from trying to resolve as single file module. We don't need them

File: test/dependencies.js [hunk 6]
```diff
@@ -82,9 +72,6 @@ describe("dependencies", function() {
 			],
 			missingDependencies: [
 				// missing single file modules
```
Comment (sokra) [inline test/dependencies.js:74]:
```suggestion
```

✅

File: test/dependencies.js [hunk 7]
```diff
@@ -47,22 +47,12 @@ describe("dependencies", function() {
 				"/a/b/package.json",
 				"/a/package.json",
 				"/package.json",
-				"/a/node_modules/package.json",
-				"/a/b/node_modules/package.json",
 				// missing modules directories
 				"/a/b/c/node_modules",
 				// not found in modules directories
```
Comment (sokra) [inline test/dependencies.js:52]:
```suggestion
```

**Review by sokra — APPROVED** [review]
Perfect.

Remove the unneeded headers from the tests.

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks
