### PR TITLE
Fixes for Windows when using symbolic links

### LINKED ISSUE #153: Infinite loop and crash using symbolic links under Windows (PR included)
# Bug report

**What is the current behavior?**
Infinite loop and runtime crash.

**If the current behavior is a bug, please provide the steps to reproduce.**
Under Windows, create a new module and use "npm link" to link it in your project, "cd" to the symlink, then create your bundle with Webpack.

**What is the expected behavior?**
Creation of my bundle without any error.

**Other relevant information:**
webpack version: 4.8.3 
Node.js version: 10.1.0
Operating System: Windows 10, 64 bits
Additional tools: enhanced-resolve@4.0.0

**Do you have a PR for us ?**
[#150](https://github.com/webpack/enhanced-resolve/pull/150)

### PR DESCRIPTION
**Pull request by doodadjs**
fixes #153 

1) "F:" resolves to the current working directory of drive "F" if the current working directory is a symbolic link. EDIT: That was causing an infinite loop.
2) Fix the Regexp to detect Windows absolute paths.
3) ~~"resolver.doResolve" was called twice with an absolute symbolic link. That fix needs more review because I'm not sure.~~ EDIT: Has been reverted and a new issue (#154) has been opened instead.

Thanks,

Claude Petit

### CODE REVIEW

**Comment by doodadjs** [comment]
I forgot to mention that this PR solves an infinite loop with Webpack 4... Will someone finally review it ?

**Comment by evilebottnawi** [comment]
@doodadjs many we can add more tests?

**Comment by doodadjs** [comment]
@evilebottnawi I tried with disabling my third fix and it still resolves the issue. I think I should remove it from the PR and open a separate issue, what do you think ?

**Comment by evilebottnawi** [comment]
@doodadjs go ahead

**Comment by doodadjs** [comment]
@evilebottnawi Done.

**Comment by evilebottnawi** [comment]
@doodadjs can you attach link on issue?

**Comment by doodadjs** [comment]
@evilebottnawi I've attached a link on the issue.

**Comment by evilebottnawi** [comment]
need @sokra review and we can merge :+1:

File: test/symlink.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ var resolve = require("../");
 var should = require("should");
 var path = require("path");
 var fs = require("fs");
+var os = require("os");
```
Comment (shellscape) [inline test/symlink.js]: `package.json` states that the node version is >= 6.9.0 for this module. there's no reason new code should be using `var` instead of `let` or `const`

also, if the only thing we're using `os` for is `platform` (see below) then use destructuring here.

File: test/symlink.js [hunk 2]
```diff
@@ -31,6 +32,10 @@ describe("symlink", function() {
 	}
 
 	if(isAdmin) {
+		// PR #150
+		var isWindows = (os.type() === "Windows_NT");
```
Comment (shellscape) [inline test/symlink.js]: ick. use `os.platform()` https://nodejs.org/api/os.html#os_os_platform

File: lib/SymlinkPlugin.js [hunk 3]
```diff
@@ -23,13 +23,18 @@ module.exports = class SymlinkPlugin {
...
+					// 'F:' resolves to the current working directory of drive 'F' if the current working directory is a symlink.
+					path += "\\";
+				}
 				fs.readlink(path, (err, result) => {
 					if(!err && result) {
 						pathSeqments[idx] = result;
 						containsSymlink = true;
 						// Shortcut when absolute symlink found
-						if(/^(\/|[a-zA-z]:($|\\))/.test(result))
+						if(/^(\/|[a-zA-Z]:($|\\))/.test(result)) {
```
Comment (shellscape) [inline lib/SymlinkPlugin.js]: did linting call for the addition of braces? if not, remove them to maintain the existing code style

File: test/symlink.js [hunk 4]
```diff
@@ -41,10 +46,18 @@ describe("symlink", function() {
 				fs.symlinkSync(path.join(tempPath, "this"), path.join(tempPath, "that"), "dir");
 				fs.symlinkSync(path.join("..", "..", "lib", "node.js"), path.join(tempPath, "node.relative.js"), "file");
 				fs.symlinkSync(path.join(".", "node.relative.js"), path.join(tempPath, "node.relative.sym.js"), "file");
+				// PR #150
+				if(isWindows) {
+					process.chdir(path.join(tempPath, "that"));
```
Comment (shellscape) [inline test/symlink.js]: document this addition, explain why it's necessary

File: test/symlink.js [hunk 5]
```diff
@@ -84,7 +97,7 @@ describe("symlink", function() {
 			[path.join(tempPath, "that"), "./test/temp/lib/node.js", "with symlinked directory as context and in path (chained)"],
 			[path.join(tempPath, "that", "lib"), "./node.js", "with symlinked directory in context path (chained)"],
 			[path.join(tempPath, "that", "test"), "./temp/node.js", "with symlinked directory in context path and symlinked file (chained)"],
-			[path.join(tempPath, "that", "test"), "./temp/lib/node.js", "with symlinked directory in context path and symlinked directory (chained)"],
+			[path.join(tempPath, "that", "test"), "./temp/lib/node.js", "with symlinked directory in context path and symlinked directory (chained)"]
```
Comment (shellscape) [inline test/symlink.js]: was the trailing comma removed due to a linting error? if not, please restore it to maintain the original code style

File: test/symlink.js [hunk 6]
```diff
@@ -31,6 +34,10 @@ describe("symlink", function() {
 	}
 
 	if(isAdmin) {
+		// PR #150: Detect Windows and preserve current working directory.
+		var isWindows = (platform() === "win32");
```
Comment (shellscape) [inline test/symlink.js]: vars

**Comment by doodadjs** [comment]
@shellscape  There is a conflict between setups of ESLint and beautify-lint, can you help me ?

**Comment by doodadjs** [comment]
@shellscape Conflict solved... Now how to fix Codecov always complaining on every commit ?

**Comment by sokra** [comment]
It would be great to get windows CI for this repo. But this is a story for another PR.

**Comment by sokra** [comment]
Thanks

**Comment by doodadjs** [comment]
@sokra Your changes don't work for me.... Did the tests passed on Windows ?
